//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ans.Net6.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _ResErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _ResErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ans.Net6.Common._ResErrors", typeof(_ResErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ &apos;{0}&apos; отсутствует в файле конфигурации приложения.
        /// </summary>
        public static string Template_AppConfig_KeyDoesNotExist {
            get {
                return ResourceManager.GetString("Template_AppConfig_KeyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОШИБКА: {0}.
        /// </summary>
        public static string Template_ErrorMessage {
            get {
                return ResourceManager.GetString("Template_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Массив байтов не прочитан должным образом.
        /// </summary>
        public static string Text_Crypto_ReadArrayFail {
            get {
                return ResourceManager.GetString("Text_Crypto_ReadArrayFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поток не содержит правильно отформатированный массив байтов.
        /// </summary>
        public static string Text_Crypto_StreamFormatFail {
            get {
                return ResourceManager.GetString("Text_Crypto_StreamFormatFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось распознать формат изображения.
        /// </summary>
        public static string Text_Graph_ImageFormatFail {
            get {
                return ResourceManager.GetString("Text_Graph_ImageFormatFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточная длина номера.
        /// </summary>
        public static string Text_Phone_InsufficientLengthOfNumber {
            get {
                return ResourceManager.GetString("Text_Phone_InsufficientLengthOfNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный дополнительный код.
        /// </summary>
        public static string Text_Phone_InvalidOfAdditional {
            get {
                return ResourceManager.GetString("Text_Phone_InvalidOfAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный код города.
        /// </summary>
        public static string Text_Phone_InvalidOfCityCode {
            get {
                return ResourceManager.GetString("Text_Phone_InvalidOfCityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректное примечание.
        /// </summary>
        public static string Text_Phone_InvalidOfNotation {
            get {
                return ResourceManager.GetString("Text_Phone_InvalidOfNotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный номер.
        /// </summary>
        public static string Text_Phone_InvalidOfNumber {
            get {
                return ResourceManager.GetString("Text_Phone_InvalidOfNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка XML/XSLT преобразования.
        /// </summary>
        public static string Text_XmlXslt_TransformationFail {
            get {
                return ResourceManager.GetString("Text_XmlXslt_TransformationFail", resourceCulture);
            }
        }
    }
}
